# Generated by Django 6.0.6 on 2026-06-27 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0001_initial'),
        ('incentive_calculator', '0002_incentivecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIncentiveTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_trigger', to='customer_dashboard.customer')),
            ],
        ),
    ]
