# Generated by Django 6.0.6 on 2026-06-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incentive_calculator', '0003_customerincentivetrigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerincentivetrigger',
            name='updated_at',
        ),
    ]
