# Generated by Django 5.2.4 on 2026-08-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0010_alter_customercreditprofile_credit_period_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossSellingRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_selling_remarks', to='customer_dashboard.customer')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_selling_remarks', to='customer_dashboard.salesperson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
