# Generated by Django 6.0.5 on 2026-05-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryitem_expected_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expected_delivery_days',
            field=models.IntegerField(blank=True, help_text='Number of days expected for delivery after placing a purchase order', null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='minimum_order_quantity',
            field=models.IntegerField(blank=True, help_text='Minimum quantity that must be ordered from the supplier in a single batch', null=True),
        ),
    ]
