# Generated by Django 5.2.4 on 2026-09-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_purchaseordertracking_manual_eta_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailystockdata',
            index=models.Index(fields=['date'], name='inventory_d_date_8c3673_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystockdata',
            index=models.Index(fields=['date', 'outwards_quantity'], name='inventory_d_date_f7c1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystockdata',
            index=models.Index(fields=['product', 'date'], name='inventory_d_product_8f23c8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['quantity'], name='inventory_i_quantit_82f142_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['min_quantity'], name='inventory_i_min_qua_83a1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['min_quantity_outwards'], name='inventory_i_min_qua_4ae812_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlystockdata',
            index=models.Index(fields=['year', 'month'], name='inventory_m_year_da5006_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlystockdata',
            index=models.Index(fields=['product', 'year', 'month'], name='inventory_m_product_26c92d_idx'),
        ),
    ]
