# Generated by Django 5.2.4 on 2026-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_dailystockdata_inventory_d_date_8c3673_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_head', 'Sales Head'), ('business_manager', 'Business Manager'), ('hr', 'HR'), ('accounts_operations', 'Accounts & Operations'), ('warehouse', 'Warehouse'), ('rsm', 'Regional Sales Manager'), ('asm', 'Area Sales Manager'), ('salesperson', 'Salesperson')], db_index=True, default='salesperson', help_text='Primary business role for access control.', max_length=30),
        ),
    ]
