# Generated by Django 5.2.4 on 2026-09-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_dailystockdata_inventory_d_date_8c3673_idx_and_more'),
        ('tally_voucher', '0003_voucheremipaymentallocation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['voucher_type', 'date'], name='tally_vouch_voucher_5239cd_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['date'], name='tally_vouch_date_741c15_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherstockitem',
            index=models.Index(fields=['voucher', 'item'], name='tally_vouch_voucher_a345dd_idx'),
        ),
    ]
