# Generated by Django 6.0.6 on 2026-06-19 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_purchaseorderstage_purchaseordertracking_and_more'),
        ('proforma_invoice', '0008_creditperiodoverduebypassrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformastockshortagerequest',
            name='shortage_details',
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='proformastockshortagerequest',
            name='requested_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proformastockshortagerequest',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='proforma_invoice.proformainvoice'),
        ),
    ]
