# Generated by Django 6.0.6 on 2026-06-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0009_remove_proformastockshortagerequest_shortage_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Snapshot of quantity at time of request', null=True),
        ),
    ]
