# Generated by Django 6.0.6 on 2026-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0010_proformapricechangerequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditperiodoverduebypassrequest',
            name='overdue_snapshot',
            field=models.JSONField(blank=True, help_text='Frozen list of overdue invoices at the time of request', null=True),
        ),
    ]
