# Generated by Django 6.0.6 on 2026-07-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0011_creditperiodoverduebypassrequest_overdue_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditperiodoverduebypassrequest',
            name='overdue_snapshot',
        ),
    ]
