# Generated by Django 6.0.6 on 2026-07-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0012_remove_creditperiodoverduebypassrequest_overdue_snapshot'),
        ('tally_voucher', '0003_voucheremipaymentallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPeriodOverdueInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days_overdue_snapshot', models.PositiveIntegerField()),
                ('voucher_date_snapshot', models.DateField()),
                ('bypass_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_invoices', to='proforma_invoice.creditperiodoverduebypassrequest')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tally_voucher.voucher')),
            ],
        ),
    ]
