# Generated by Django 6.1 on 2026-08-26 10:12

import django.db.models.deletion
import proforma_invoice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0011_crosssellingremark'),
        ('inventory', '0009_purchaseorderstage_purchaseordertracking_and_more'),
        ('proforma_invoice', '0013_creditperiodoverdueinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tracking_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='proformapricechangerequest',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='proforma_invoice.proformainvoice'),
        ),
        migrations.AlterField(
            model_name='proformaremark',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='proforma_invoice.proformainvoice'),
        ),
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('waiting_for_packing', 'Waiting For Packing'), ('packed_awaiting_approval', 'Packed - Awaiting Approval'), ('packing_approved', 'Packing Approved'), ('dispatched_by_warehouse', 'Dispatched By Warehouse'), ('completed', 'Completed'), ('packing_rejected', 'Packing Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_request', to='proforma_invoice.proformainvoice')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shipment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proforma_invoice.shipmentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='proforma_invoice.dispatchrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=proforma_invoice.models.dispatch_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='proforma_invoice.dispatchrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=proforma_invoice.models.dispatch_invoice_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_file', to='proforma_invoice.dispatchrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='proforma_invoice.dispatchrequest')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('validity', models.DateTimeField(default=proforma_invoice.models.validity_default)),
                ('created_by', models.CharField(default='Oblu', max_length=255)),
                ('is_price_altered', models.BooleanField(default=False)),
                ('courier_mode', models.CharField(choices=[('surface', 'Surface'), ('air', 'Air')], default='surface', max_length=10)),
                ('is_converted_to_proforma', models.BooleanField(default=False, help_text='True if this quotation was converted to a Proforma Invoice')),
                ('converted_at', models.DateTimeField(blank=True, help_text='Timestamp when converted to PI', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_dashboard.customer')),
                ('shipping_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_shipping', to='customer_dashboard.customer')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='proformapricechangerequest',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='proforma_invoice.quotationmaker'),
        ),
        migrations.AddField(
            model_name='proformaremark',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='proforma_invoice.quotationmaker'),
        ),
        migrations.CreateModel(
            name='QuotationMakerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_courier_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Current - courier', max_digits=10)),
                ('requested_courier_charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Requested - courier', max_digits=10)),
                ('made_by', models.CharField(blank=True, help_text='made-by', max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proforma_invoice.quotationmaker')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docket_number', models.CharField(max_length=100)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proforma_invoice.dispatchrequest')),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CreditPeriodOverdueInvoice',
        ),
    ]
