# Generated by Django 5.2.4 on 2026-10-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proforma_invoice', '0014_shipmentmethod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchphoto',
            name='dispatch_request',
        ),
        migrations.RemoveField(
            model_name='dispatchphoto',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='dispatchremark',
            name='dispatch_request',
        ),
        migrations.RemoveField(
            model_name='dispatchremark',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dispatchrequest',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='dispatchrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='dispatchrequest',
            name='shipment_method',
        ),
        migrations.RemoveField(
            model_name='dispatchstatehistory',
            name='dispatch_request',
        ),
        migrations.RemoveField(
            model_name='warehousedispatch',
            name='dispatch_request',
        ),
        migrations.RemoveField(
            model_name='dispatchstatehistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='warehousedispatch',
            name='dispatched_by',
        ),
        migrations.DeleteModel(
            name='DispatchInvoice',
        ),
        migrations.DeleteModel(
            name='DispatchPhoto',
        ),
        migrations.DeleteModel(
            name='DispatchRemark',
        ),
        migrations.DeleteModel(
            name='ShipmentMethod',
        ),
        migrations.DeleteModel(
            name='DispatchRequest',
        ),
        migrations.DeleteModel(
            name='DispatchStateHistory',
        ),
        migrations.DeleteModel(
            name='WarehouseDispatch',
        ),
    ]
